---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - role[default]
    attributes:
